services:
  webapp:
    build: .
    volumes:
      - ./:/app
      - ./static:/mnt/web/photoshare/static
      - /mnt/photoshare/media:/mnt/web/photoshare/static/media
      - /mnt/photoshare/uploads:/mnt/web/photoshare/uploads
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FKEY=${FKEY}
      - WTFKEY=${WTFKEY}  
      - PSHR=${PSHR}
    depends_on: []
    restart: unless-stopped
    networks:
      - web

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/blockuseragents.rules:/etc/nginx/blockuseragents.rules:ro
      - ./static:/mnt/web/photoshare/static:ro
      - /mnt/photoshare/media:/mnt/web/photoshare/static/media:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - webapp
    environment:
      - DOMAIN=${DOMAIN}
    restart: unless-stopped
    networks:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email ${LETSENCRYPT_EMAIL} --agree-tos --no-eff-email --staging -d ${DOMAIN}

volumes:
  certbot-etc:
  certbot-var:
  webroot:

networks:
  web: 